// src/permissions.js

export const PERMISSIONS_LIST = [
    "TENANT_CREATE", "TENANT_VIEW", "TENANT_UPDATE", "TENANT_DELETE",
    "USER_CREATE", "USER_INVITE", "USER_VIEW", "USER_UPDATE", "USER_DELETE",
    "USER_PROFILE_CREATE", "USER_PROFILE_VIEW", "USER_PROFILE_UPDATE", "USER_PROFILE_DELETE",
    "ROLE_TYPE_CREATE", "ROLE_TYPE_VIEW", "ROLE_TYPE_UPDATE", "ROLE_TYPE_DELETE",
    "DEAL_CREATE", "DEAL_VIEW", "DEAL_UPDATE", "DEAL_DELETE",
    "MEMBER_CREATE", "MEMBER_VIEW", "MEMBER_UPDATE", "MEMBER_DELETE",
    "INVESTMENT_CREATE", "INVESTMENT_VIEW", "INVESTMENT_UPDATE", "INVESTMENT_DELETE",
    "PAYMENT_SCHEDULE_CREATE", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_SCHEDULE_UPDATE", "PAYMENT_SCHEDULE_DELETE",
    "PAYMENT_CREATE", "PAYMENT_VIEW", "PAYMENT_UPDATE", "PAYMENT_DELETE",
    "FEE_CREATE", "FEE_VIEW", "FEE_UPDATE", "FEE_DELETE",
    "DIMENTION_CREATE", "DIMENTION_VIEW", "DIMENTION_UPDATE", "DIMENTION_DELETE",
    "REPORT_CREATE", "REPORT_VIEW", "REPORT_EXPORT", "REPORT_UPDATE", "REPORT_DELETE",
    "PLATFORM_USER_CREATE", "PLATFORM_USER_DELETE", "PLATFORM_USER_VIEW", "PLATFORM_USER_UPDATE",
    "PLATFORM_TENANT_CREATE", "PLATFORM_TENANT_DELETE", "PLATFORM_TENANT_VIEW", "PLATFORM_TENANT_UPDATE",
    "CONTACT_CREATE", "CONTACT_VIEW", "CONTACT_UPDATE", "CONTACT_DELETE"
];

// Provide sensible defaults for the requested standard UserRoles.
// These are used as fallbacks if the role hasn't been explicitly configured in the Database `roles` collection.
export const DEFAULT_ROLE_PERMISSIONS = {
    "Super Admin": [...PERMISSIONS_LIST], // Full access
    "Platform Admin": [...PERMISSIONS_LIST], // Full access
    "company_super_admin_read_write": [...PERMISSIONS_LIST], // Full access
    "L2 Admin": [...PERMISSIONS_LIST], // Full access
    "Tenant Owner": [
        "TENANT_VIEW", "TENANT_UPDATE",
        "USER_CREATE", "USER_INVITE", "USER_VIEW", "USER_UPDATE", "USER_DELETE",
        "USER_PROFILE_VIEW", "USER_PROFILE_CREATE", "USER_PROFILE_UPDATE", "USER_PROFILE_DELETE",
        "ROLE_TYPE_VIEW", "ROLE_TYPE_CREATE", "ROLE_TYPE_UPDATE", "ROLE_TYPE_DELETE",
        "DEAL_CREATE", "DEAL_VIEW", "DEAL_UPDATE", "DEAL_DELETE",
        "MEMBER_CREATE", "MEMBER_VIEW", "MEMBER_UPDATE", "MEMBER_DELETE",
        "INVESTMENT_CREATE", "INVESTMENT_VIEW", "INVESTMENT_UPDATE", "INVESTMENT_DELETE",
        "PAYMENT_SCHEDULE_CREATE", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_SCHEDULE_UPDATE", "PAYMENT_SCHEDULE_DELETE",
        "PAYMENT_CREATE", "PAYMENT_VIEW", "PAYMENT_UPDATE", "PAYMENT_DELETE",
        "FEE_CREATE", "FEE_VIEW", "FEE_UPDATE", "FEE_DELETE",
        "DIMENTION_CREATE", "DIMENTION_VIEW", "DIMENTION_UPDATE", "DIMENTION_DELETE",
        "REPORT_CREATE", "REPORT_VIEW", "REPORT_EXPORT", "REPORT_UPDATE", "REPORT_DELETE",
        "CONTACT_CREATE", "CONTACT_VIEW", "CONTACT_UPDATE", "CONTACT_DELETE"
    ],
    "Tenant Admin": [
        "TENANT_VIEW",
        "USER_CREATE", "USER_INVITE", "USER_VIEW", "USER_UPDATE",
        "USER_PROFILE_VIEW", "USER_PROFILE_CREATE", "USER_PROFILE_UPDATE",
        "ROLE_TYPE_VIEW", "ROLE_TYPE_CREATE", "ROLE_TYPE_UPDATE",
        "DEAL_CREATE", "DEAL_VIEW", "DEAL_UPDATE",
        "MEMBER_CREATE", "MEMBER_VIEW", "MEMBER_UPDATE",
        "INVESTMENT_CREATE", "INVESTMENT_VIEW", "INVESTMENT_UPDATE",
        "PAYMENT_SCHEDULE_CREATE", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_SCHEDULE_UPDATE",
        "PAYMENT_CREATE", "PAYMENT_VIEW", "PAYMENT_UPDATE",
        "FEE_CREATE", "FEE_VIEW", "FEE_UPDATE",
        "DIMENTION_CREATE", "DIMENTION_VIEW", "DIMENTION_UPDATE",
        "REPORT_CREATE", "REPORT_VIEW", "REPORT_EXPORT", "REPORT_UPDATE",
        "CONTACT_CREATE", "CONTACT_VIEW", "CONTACT_UPDATE"
    ],
    "Tenant Manager": [
        "TENANT_VIEW", "USER_VIEW",
        "DEAL_CREATE", "DEAL_VIEW", "DEAL_UPDATE",
        "INVESTMENT_CREATE", "INVESTMENT_VIEW", "INVESTMENT_UPDATE",
        "PAYMENT_SCHEDULE_CREATE", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_SCHEDULE_UPDATE",
        "PAYMENT_VIEW",
        "FEE_CREATE", "FEE_VIEW", "FEE_UPDATE",
        "REPORT_VIEW", "REPORT_EXPORT",
        "CONTACT_CREATE", "CONTACT_VIEW", "CONTACT_UPDATE"
    ],
    "Tenant Member": [
        "TENANT_VIEW", "USER_VIEW",
        "DEAL_VIEW", "INVESTMENT_VIEW", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_VIEW", "FEE_VIEW", "REPORT_VIEW", "CONTACT_VIEW"
    ],
    "Tenant Viewer": [
        "DEAL_VIEW", "INVESTMENT_VIEW", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_VIEW", "FEE_VIEW", "REPORT_VIEW", "CONTACT_VIEW"
    ],
    "Auditor": [
        "TENANT_VIEW", "USER_VIEW", "DEAL_VIEW", "MEMBER_VIEW", "INVESTMENT_VIEW",
        "PAYMENT_SCHEDULE_VIEW", "PAYMENT_VIEW", "FEE_VIEW", "DIMENTION_VIEW", "REPORT_VIEW", "REPORT_EXPORT", "CONTACT_VIEW"
    ],
    "Support Admin": [
        "TENANT_VIEW", "USER_VIEW", "DEAL_VIEW", "INVESTMENT_VIEW", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_VIEW", "FEE_VIEW", "DIMENTION_VIEW", "CONTACT_VIEW"
    ],
    "Platform_Operator": [
        "PLATFORM_USER_CREATE", "PLATFORM_USER_VIEW", "PLATFORM_USER_UPDATE", "PLATFORM_USER_DELETE",
        "PLATFORM_TENANT_VIEW", "TENANT_VIEW",
        "DEAL_VIEW", "INVESTMENT_VIEW", "CONTACT_VIEW",
        "PAYMENT_SCHEDULE_VIEW", "PAYMENT_VIEW", "FEE_VIEW",
        "REPORT_VIEW", "REPORT_EXPORT"
    ]
};
