// src/permissions.js

export const PERMISSIONS_LIST = [
    "TENANT_CREATE", "TENANT_VIEW", "TENANT_UPDATE", "TENANT_DELETE",
    "USER_CREATE", "USER_INVITE", "USER_VIEW", "USER_UPDATE", "USER_DELETE",
    "PROJECT_CREATE", "PROJECT_VIEW", "PROJECT_UPDATE", "PROJECT_DELETE",
    "MEMBER_CREATE", "MEMBER_VIEW", "MEMBER_UPDATE", "MEMBER_DELETE",
    "CONTRACT_CREATE", "CONTRACT_VIEW", "CONTRACT_UPDATE", "CONTRACTS_DELETE",
    "PAYMENT_SCHEDULE_CREATE", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_SCHEDULE_UPDATE", "PAYMENT_SCHEDULE_DELETE",
    "FEE_CREATE", "FEE_VIEW", "FEE_UPDATE", "FEE_DELETE",
    "DIMENTION_CREATE", "DIMENTION_VIEW", "DIMENTION_UPDATE", "DIMENTION_DELETE",
    "REPORT_CREATE", "REPORT_VIEW", "REPORT_EXPORT", "REPORT_UPDATE", "REPORT_DELETE",
    "PLATFORM_USER_CREATE", "PLATFORM_USER_DELETE", "PLATFORM_USER_VIEW", "PLATFORM_USER_UPDATE",
    "PARTY_CREATE", "PARTY_VIEW", "PARTY_UPDATE", "PARTY_DELETE"
];

// Provide sensible defaults for the requested standard UserRoles.
// These are used as fallbacks if the role hasn't been explicitly configured in the Database `roles` collection.
export const DEFAULT_ROLE_PERMISSIONS = {
    "Super Admin": [...PERMISSIONS_LIST], // Full access
    "Platform Admin": [...PERMISSIONS_LIST], // Full access
    "company_super_admin_read_write": [...PERMISSIONS_LIST], // Full access
    "L2 Admin": [...PERMISSIONS_LIST], // Full access
    "Tenant Owner": [
        "TENANT_VIEW", "TENANT_UPDATE",
        "USER_CREATE", "USER_INVITE", "USER_VIEW", "USER_UPDATE", "USER_DELETE",
        "PROJECT_CREATE", "PROJECT_VIEW", "PROJECT_UPDATE", "PROJECT_DELETE",
        "MEMBER_CREATE", "MEMBER_VIEW", "MEMBER_UPDATE", "MEMBER_DELETE",
        "CONTRACT_CREATE", "CONTRACT_VIEW", "CONTRACT_UPDATE", "CONTRACTS_DELETE",
        "PAYMENT_SCHEDULE_CREATE", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_SCHEDULE_UPDATE", "PAYMENT_SCHEDULE_DELETE",
        "FEE_CREATE", "FEE_VIEW", "FEE_UPDATE", "FEE_DELETE",
        "DIMENTION_CREATE", "DIMENTION_VIEW", "DIMENTION_UPDATE", "DIMENTION_DELETE",
        "REPORT_CREATE", "REPORT_VIEW", "REPORT_EXPORT", "REPORT_UPDATE", "REPORT_DELETE",
        "PARTY_CREATE", "PARTY_VIEW", "PARTY_UPDATE", "PARTY_DELETE"
    ],
    "Tenant Admin": [
        "TENANT_VIEW",
        "USER_CREATE", "USER_INVITE", "USER_VIEW", "USER_UPDATE",
        "PROJECT_CREATE", "PROJECT_VIEW", "PROJECT_UPDATE",
        "MEMBER_CREATE", "MEMBER_VIEW", "MEMBER_UPDATE",
        "CONTRACT_CREATE", "CONTRACT_VIEW", "CONTRACT_UPDATE",
        "PAYMENT_SCHEDULE_CREATE", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_SCHEDULE_UPDATE",
        "FEE_CREATE", "FEE_VIEW", "FEE_UPDATE",
        "DIMENTION_CREATE", "DIMENTION_VIEW", "DIMENTION_UPDATE",
        "REPORT_CREATE", "REPORT_VIEW", "REPORT_EXPORT", "REPORT_UPDATE",
        "PARTY_CREATE", "PARTY_VIEW", "PARTY_UPDATE"
    ],
    "Tenant Manager": [
        "TENANT_VIEW", "USER_VIEW",
        "PROJECT_CREATE", "PROJECT_VIEW", "PROJECT_UPDATE",
        "CONTRACT_CREATE", "CONTRACT_VIEW", "CONTRACT_UPDATE",
        "PAYMENT_SCHEDULE_CREATE", "PAYMENT_SCHEDULE_VIEW", "PAYMENT_SCHEDULE_UPDATE",
        "FEE_CREATE", "FEE_VIEW", "FEE_UPDATE",
        "REPORT_VIEW", "REPORT_EXPORT",
        "PARTY_CREATE", "PARTY_VIEW", "PARTY_UPDATE"
    ],
    "Tenant Member": [
        "TENANT_VIEW", "USER_VIEW",
        "PROJECT_VIEW", "CONTRACT_VIEW", "PAYMENT_SCHEDULE_VIEW", "FEE_VIEW", "REPORT_VIEW", "PARTY_VIEW"
    ],
    "Tenant Viewer": [
        "PROJECT_VIEW", "CONTRACT_VIEW", "PAYMENT_SCHEDULE_VIEW", "FEE_VIEW", "REPORT_VIEW", "PARTY_VIEW"
    ],
    "Auditor": [
        "TENANT_VIEW", "USER_VIEW", "PROJECT_VIEW", "MEMBER_VIEW", "CONTRACT_VIEW",
        "PAYMENT_SCHEDULE_VIEW", "FEE_VIEW", "DIMENTION_VIEW", "REPORT_VIEW", "REPORT_EXPORT", "PARTY_VIEW"
    ],
    "Support Admin": [
        "TENANT_VIEW", "USER_VIEW", "PROJECT_VIEW", "CONTRACT_VIEW", "PAYMENT_SCHEDULE_VIEW", "FEE_VIEW", "DIMENTION_VIEW", "PARTY_VIEW"
    ],
    "Platform_Operator": [
        "PLATFORM_USER_VIEW", "TENANT_VIEW"
    ]
};
